GET http://localhost:3001/

###
GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/634726c3bc5a83a7b678500f

###

DELETE http://localhost:3001/api/persons/6349cfc64843093b43544c1e

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "rosa",
    "number": "12-121212"
}

###

PUT http://localhost:3001/api/persons/
Content-Type: application/json

{

    "number": "788-7777"
}