GET http://localhost:3001/

###
GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/634726c3bc5a83a7b678500f

###

DELETE http://localhost:3001/api/persons/6349cfc64843093b43544c1e

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Roberto",
    "number": "12-12-1212"
}

###

PUT http://localhost:3001/api/persons/6349d8e7a8af97087c6c6805
Content-Type: application/json

{
    "number": "78-87-9669"
}